Repository YAPP-Github/21st-iOS-Team-2-iOS, pull requests merged in 2022-12, with the labels that each got.

#2 [Feature] 초기 화면 설정
  Fitfty/Projects/App/Sources/Application/SceneDelegate.swift
  Fitfty/Projects/Auth/Sources/Auth.swift
  Fitfty/Projects/Auth/Sources/AuthCoordinatorInterface.swift
  Fitfty/Projects/Auth/Sources/AuthViewController.swift
  Fitfty/Projects/Coordinator/Sources/AppCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/AuthCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
Labels: ✨기능, D-0

#4 [Feature] 폰트 추가
  Fitfty/Projects/Auth/Sources/AuthViewController.swift
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoB.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoEB.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoH.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoL.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoM.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoR.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoSB.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoT.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/AppleSDGothicNeoUL.ttf
  Fitfty/Projects/Common/Sources/FitftyFont.swift
Labels: D-0, 💄UI

#5 [Feature] ViewModel 예시코드 작성
  Fitfty/Projects/Auth/Sources/AuthCoordinatorInterface.swift
  Fitfty/Projects/Auth/Sources/AuthViewController.swift
  Fitfty/Projects/Auth/Sources/AuthViewModel.swift
  Fitfty/Projects/Common/Sources/ViewModelType.swift
  Fitfty/Projects/Coordinator/Sources/AuthCoordinator.swift
Labels: ✨기능, D-2

#6 [Feature] 메인화면 UI 구현
  Fitfty/.swiftlint.yml
  Fitfty/Projects/Common/Resources/Colors.xcassets/FT.colorset/Contents.json
  Fitfty/Projects/Common/Resources/Colors.xcassets/FTSecondaryText.colorset/Contents.json
  Fitfty/Projects/Common/Resources/Colors.xcassets/FTtext.colorset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/Image.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_add.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_add.imageset/icon_add.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_profile.fill.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_profile.fill.imageset/icon_profile.fill.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_profile.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_profile.imageset/icon_profile.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_sun.fill.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_sun.fill.imageset/icon_sun.fill.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_sun.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_sun.imageset/icon_sun.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/sample.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/sample.imageset/sample.png
  Fitfty/Projects/Common/Sources/Extension/NSObject+extension.swift
  Fitfty/Projects/Common/Sources/Extension/UICollectionView+extension.swift
  Fitfty/Projects/Common/Sources/Extension/UIFont+extension.swift
  Fitfty/Projects/Common/Sources/Extension/UIStackView+extension.swift
  Fitfty/Projects/Common/Sources/Extension/UIView+extension.swift
  Fitfty/Projects/Coordinator/Sources/AppCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/AuthCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/MainCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/MainFeed/Sources/MainCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/MainFeed.swift
  Fitfty/Projects/MainFeed/Sources/ViewControllers/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/ViewControllers/TabBarController.swift
  Fitfty/Projects/MainFeed/Sources/Views/CodyCell.swift
  Fitfty/Projects/MainFeed/Sources/Views/FooterView.swift
  Fitfty/Projects/MainFeed/Sources/Views/HeaderView.swift
  Fitfty/Projects/MainFeed/Sources/Views/LocationView.swift
  Fitfty/Projects/MainFeed/Sources/Views/StyleCell.swift
  Fitfty/Projects/MainFeed/Sources/Views/WeatherCell.swift
  Fitfty/Projects/MainFeed/Sources/Views/WeatherInfoHeaderView.swift
  Fitfty/Projects/MainFeed/Sources/Views/WeatherInfoView.swift
  Fitfty/Projects/Onboarding/Project.swift
Labels: ♻️리팩토링, D-4, 💄UI

#7 [Feature] 프로필 UI 구현
  Fitfty/Projects/Common/Resources/CustomFonts/SF-Pro-Display-Black.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/SF-Pro-Display-Bold.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/SF-Pro-Display-Light.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/SF-Pro-Display-Medium.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/SF-Pro-Display-Semibold.ttf
  Fitfty/Projects/Common/Resources/CustomFonts/SF-Pro-Display-Thin.ttf
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkSelected.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkSelected.imageset/btnBookmarkSelected.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkSelected.imageset/btnBookmarkSelected@2x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkSelected.imageset/btnBookmarkSelected@3x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkUnselected.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkUnselected.imageset/btnBookmarkUnselected.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkUnselected.imageset/btnBookmarkUnselected@2x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnBookmarkUnselected.imageset/btnBookmarkUnselected@3x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodySelected.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodySelected.imageset/btnCodySelected.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodySelected.imageset/btnCodySelected@2x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodySelected.imageset/btnCodySelected@3x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodyUnselected.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodyUnselected.imageset/btnCodyUnselected.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodyUnselected.imageset/btnCodyUnselected@2x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/btnCodyUnselected.imageset/btnCodyUnselected@3x.png
  Fitfty/Projects/Common/Resources/Images.xcassets/profileSample.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/profileSample.imageset/Image.png
  Fitfty/Projects/Common/Sources/FitftyFont.swift
  Fitfty/Projects/Profile/Sources/Profile.swift
  Fitfty/Projects/Profile/Sources/View/FeedImageCell.swift
  Fitfty/Projects/Profile/Sources/View/HeaderView.swift
  Fitfty/Projects/Profile/Sources/View/MenuView.swift
  Fitfty/Projects/Profile/Sources/View/ProfileView.swift
  Fitfty/Projects/Profile/Sources/ViewController/ProfileViewController.swift
Labels: D-4, 💄UI

#8 [Feature] 날씨 API 구현
  Fitfty/.gitignore
  Fitfty/Projects/App/Project.swift
  Fitfty/Projects/App/Support/Info.plist
  Fitfty/Projects/Core/Sources/APIKey.swift
  Fitfty/Projects/Core/Sources/Core.swift
  Fitfty/Projects/Core/Sources/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/WeatherAPI.swift
  Fitfty/Projects/Core/Tests/CoreTests.swift
  Fitfty/Projects/Core/Tests/WeatherAPITest.swift
Labels: ✨기능, D-3
