Repository YAPP-Github/21st-iOS-Team-2-iOS, pull requests merged in 2023-02, with the labels that each got.

#21 [Fix] UploadCodyViewController를 dismiss할 때 메모리가 해제되지 않는 현상 개선
  Fitfty/Projects/Coordinator/Sources/Main/UploadCodyCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewController/WeatherViewController.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/ViewControllers/AlbumViewController.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/ViewControllers/UploadCodyViewController.swift
  Fitfty/Projects/Setting/Sources/Home/ViewController/SettingViewController.swift
Labels: 🐛 버그, ♻️리팩토링, D-1

#26 [Feature] Fitfty API 구현
  Fitfty/.swiftlint.yml
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Utilities/APIKey.swift
Labels: 🖥네트워킹, D-1

#25 [Feature] 메인피드 View Model 구현
  Fitfty/Projects/App/Support/Info.plist
  Fitfty/Projects/Common/Resources/Images.xcassets/weather.imageset/weather.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/weather/cloudAndSun.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/weather/cloudAndSun.imageset/cloudAndSun.svg
  Fitfty/Projects/Common/Sources/BottomSheetViewController.swift
  Fitfty/Projects/Common/Sources/ErrorNotiView.swift
  Fitfty/Projects/Common/Sources/Extension/Publisher+MainThread.swift
  Fitfty/Projects/Common/Sources/Extension/UIViewController+extension.swift
  Fitfty/Projects/Common/Sources/FooterView.swift
  Fitfty/Projects/Common/Sources/HeaderView.swift
  Fitfty/Projects/Common/Sources/LoadingView.swift
  Fitfty/Projects/Coordinator/Sources/Main/AddressCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/AlbumCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/MainCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/WelcomeCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/FeedSettingCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ProfileSettingCoordinator.swift
  Fitfty/Projects/Core/Sources/LocalStorage.swift
  Fitfty/Projects/Core/Sources/Model/Address.swift
  Fitfty/Projects/Core/Sources/Model/MidTermForecast.swift
  Fitfty/Projects/Core/Sources/Model/ShortTermForecast.swift
  Fitfty/Projects/Core/Sources/Network/Response/KakaoAK/AddressConversionResponse.swift
  Fitfty/Projects/Core/Sources/Network/WeatherAPI.swift
  Fitfty/Projects/Core/Sources/Repositories/AddressRepository.swift
  Fitfty/Projects/Core/Sources/Utilities/LocationManager.swift
  Fitfty/Projects/Core/Sources/Utilities/MoyaCacheablePlugin.swift
  Fitfty/Projects/Core/Sources/Utilities/UserManager.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewController/AddressViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainFeedSection.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/WeatherInfoHeaderViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/CodyCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/LocationView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/WeatherCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/WeatherInfoHeaderView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/WeatherInfoView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewController/WeatherViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/Views/WeatherIconView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/Views/WeeklyWeatherCell.swift
Labels: 🐛 버그, ♻️리팩토링, ✨기능, D-2

#29 [Feature] 내 핏프티 수정 UI, 앨범 목록에서 사진 가져오기 구현
  Fitfty/Projects/Common/Sources/BarView.swift
  Fitfty/Projects/Common/Sources/Extension/Notification.Name+extension.swift
  Fitfty/Projects/Common/Sources/MyFitftyType.swift
  Fitfty/Projects/Common/Sources/StyleTag.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/AlbumCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/AlbumListCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/MyFitftyCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/PostCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ProfileCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/AlbumCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/AlbumListCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/MyFitftyCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Delegate/ContentDelegate.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Model/AlbumInfo.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Model/PHAssetInfo.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumListViewController.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumListSection.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumListViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumSection.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftySection.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/Album/AlbumCell.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/Album/AlbumListCell.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/UploadCody/ContentCell.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/UploadCody/StyleTagCell.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/UploadCody/WeatherTagCell.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/Album/AlbumCell.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/UploadCody/ContentCell.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/PostCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/ProfileCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/Post/ViewControllers/MyPostBottomSheetViewController.swift
Labels: ✨기능, D-2, 💄UI

#27 [Feature] 주소 설정 화면 View Model 구현
  Fitfty/Projects/Coordinator/Sources/Main/AddressCoordinator.swift
  Fitfty/Projects/Core/Sources/Model/Address.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/AddressCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewController/AddressViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewModel/AddressSection.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewModel/AddressViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/Views/AddressCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/Views/AddressInfoView.swift
Labels: ✨기능, D-2

#28 [Refactor] 메인피드 UI 중 스타일 태그 Cell 레이아웃 피그마 반영하여 수정
  Fitfty/Projects/Common/Resources/Images.xcassets/Filter.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/Filter.imageset/Filter.svg
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/StyleCell.swift
Labels: D-2, 💄UI

#32 [Feature] 날씨 레파지토리에 추가 기능 구현
  Fitfty/Projects/Core/Sources/Repositories/WeatherRepository.swift
Labels: ✨기능, D-1

#31 [Feature] Amplify 라이브러리 설치 및 AmplifyManager 구현
  Fitfty/.gitignore
  Fitfty/.package.resolved
  Fitfty/Projects/App/Project.swift
  Fitfty/Projects/App/Sources/Application/AppDelegate.swift
  Fitfty/Projects/Coordinator/Project.swift
  Fitfty/Projects/Core/Project.swift
  Fitfty/Projects/Core/Sources/Utilities/AmplifyManager.swift
  Fitfty/Projects/MainFeed/Project.swift
  Fitfty/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨기능, D-2

#30 [Feature] 날씨 상세 화면 ViewModel 구현
  Fitfty/Projects/Coordinator/Sources/Main/WeatherCoordinator.swift
  Fitfty/Projects/Core/Sources/Model/MidTermForecast.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewController/AddressViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewModel/AddressViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewController/WeatherViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewModel/WeatherSection.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewModel/WeatherViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/Views/WeatherIconView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/Views/WeeklyWeatherCell.swift
Labels: ✨기능, D-2

#33 [Feature] Auth 모듈 작업
  Fitfty/.swiftlint.yml
  Fitfty/Projects/App/Project.swift
  Fitfty/Projects/App/Sources/Application/AppDelegate.swift
  Fitfty/Projects/App/Sources/Application/SceneDelegate.swift
  Fitfty/Projects/App/Support/Info.plist
  Fitfty/Projects/Auth/Project.swift
  Fitfty/Projects/Auth/Sources/Auth/AuthView.swift
  Fitfty/Projects/Auth/Sources/Auth/AuthViewController.swift
  Fitfty/Projects/Auth/Sources/Auth/AuthViewModel.swift
  Fitfty/Projects/Auth/Sources/AuthViewController.swift
  Fitfty/Projects/Auth/Sources/AuthViewModel.swift
  Fitfty/Projects/Auth/Sources/CoordinatorInterfaces/AuthCoordinatorInterface.swift
  Fitfty/Projects/Auth/Sources/CoordinatorInterfaces/FiftyLaunchScreenCoordinatorInterface.swift
  Fitfty/Projects/Auth/Sources/Intro/AuthIntroView.swift
  Fitfty/Projects/Auth/Sources/Intro/AuthIntroViewController.swift
  Fitfty/Projects/Auth/Sources/LaunchScreen/FitftyLaunchScreenViewController.swift
  Fitfty/Projects/Auth/Sources/LaunchScreen/FitftyLaunchScreenViewModel.swift
  Fitfty/Projects/Auth/Sources/Permission/AuthPermissionView.swift
  Fitfty/Projects/Auth/Sources/Permission/AuthPermissionViewController.swift
  Fitfty/Projects/Common/Resources/Images.xcassets/IntroImage.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/IntroImage.imageset/IntroImage.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/appleLoginImage.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/appleLoginImage.imageset/appleLoginImage.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/bellIcon.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/bellIcon.imageset/bell.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/fitftyLogoImage.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/fitftyLogoImage.imageset/fitftyLogoImage.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/instagramForPermission.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/instagramForPermission.imageset/instagram.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/kakaoLoginImage.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/kakaoLoginImage.imageset/kakaoLoginImage.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/mapPinIcon.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/mapPinIcon.imageset/map-pin.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/permissionImageView.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/permissionImageView.imageset/permissionImageView.svg
  Fitfty/Projects/Coordinator/Sources/AppCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Auth/AuthCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Auth/FitftyLaunchScreenCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Core/Project.swift
  Fitfty/Projects/Core/Sources/Error/SocialLoginError.swift
  Fitfty/Projects/Core/Sources/LocalStorage.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Network/Request/Auth/SocialLoginRequest.swift
  Fitfty/Projects/Core/Sources/Network/Response/Auth/SocialLoginResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/UserPrivacyResponse.swift
  Fitfty/Projects/Core/Sources/SessionManager.swift
  Fitfty/Projects/Core/Sources/SocialLoginManager.swift
  Fitfty/Projects/Core/Sources/Utilities/APIKey.swift
  Fitfty/Projects/Core/Sources/Utilities/KeyChain.swift
  Fitfty/Tuist/Dependencies.swift
  Fitfty/Tuist/ProjectDescriptionHelpers/Dependency+SPM.swift
  Fitfty/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨기능, D-2

#37 [Feature] 메인 피드 ViewModel 구현
  Fitfty/Projects/Auth/Project.swift
  Fitfty/Projects/Common/Project.swift
  Fitfty/Projects/Common/Sources/ErrorNotiView.swift
  Fitfty/Projects/Common/Sources/FeedSettingCell.swift
  Fitfty/Projects/Common/Sources/StyleTag.swift
  Fitfty/Projects/Common/Sources/WeatherTag.swift
  Fitfty/Projects/Coordinator/Sources/Main/MainCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/WelcomeCoordinator.swift
  Fitfty/Projects/Core/Sources/LocalStorage.swift
  Fitfty/Projects/Core/Sources/Model/Gender.swift
  Fitfty/Projects/Core/Sources/Model/Tag.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Network/Request/Fitfty/CodyListRequest.swift
  Fitfty/Projects/Core/Sources/Network/Response/Fitfty/BookmarkResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Fitfty/CodyListResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Fitfty/MyTagsResponse.swift
  Fitfty/Projects/Core/Sources/Repositories/FitftyRepository.swift
  Fitfty/Projects/Core/Sources/Repositories/WeatherRepository.swift
  Fitfty/Projects/Core/Sources/Utilities/UserManager.swift
  Fitfty/Projects/Core/Sources/Utilities/WeatherTransferService.swift
  Fitfty/Projects/MainFeed/Project.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/MainCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Utilities/ViewModelError.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/CodyCellViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainFeedSection.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/WeatherInfoHeaderViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/CodyCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/StyleCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/WeatherInfoHeaderView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewModel/WeatherViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Welcome/ViewController/WelcomeViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Welcome/ViewModel/WelcomeViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
  Fitfty/Projects/Onboarding/Project.swift
  Fitfty/Projects/Profile/Project.swift
  Fitfty/Projects/Profile/Sources/Post/Views/PostView.swift
  Fitfty/Projects/Setting/Project.swift
  Fitfty/Tuist/Dependencies.swift
  Fitfty/Tuist/ProjectDescriptionHelpers/Dependency+SPM.swift
Labels: ✨기능, D-1

#38 [Feature] Setting 모듈 작업
  Fitfty/Projects/Common/Resources/Images.xcassets/introImage1.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/introImage1.imageset/introImage1.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/introImage2.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/introImage2.imageset/introImage2.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/introImage3.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/introImage3.imageset/introImage3.svg
  Fitfty/Projects/Common/Sources/FitftyTextField.swift
  Fitfty/Projects/Coordinator/Sources/AppCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Setting/FeedSettingCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Setting/PersonalInfoCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Setting/ProfileSettingCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Setting/SettingCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/Core/Sources/Error/SettingError.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Network/Request/Setting/SettingUserProfileRequest.swift
  Fitfty/Projects/Core/Sources/Network/Request/Setting/UserPrivacyRequest.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/UserDetailResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/UserPrivacyResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/WithdrawAccountResponse.swift
  Fitfty/Projects/Core/Sources/Repositories/SettingRepository.swift
  Fitfty/Projects/Core/Sources/SessionManager.swift
  Fitfty/Projects/Core/Sources/Utilities/KeyChain.swift
  Fitfty/Projects/Setting/Project.swift
  Fitfty/Projects/Setting/Sources/Home/ViewController/SettingViewController.swift
  Fitfty/Projects/Setting/Sources/Home/WebView/SettingWebViewController.swift
  Fitfty/Projects/Setting/Sources/PersonalInfo/ViewController/PersonalInfoViewController.swift
  Fitfty/Projects/Setting/Sources/PersonalInfo/ViewModel/PersonalInfoViewModel.swift
  Fitfty/Projects/Setting/Sources/PersonalInfoCoordinatorInterface.swift
  Fitfty/Projects/Setting/Sources/Profile/ViewController/ProfileSettingViewController.swift
  Fitfty/Projects/Setting/Sources/Profile/ViewModel/ProfileSettingViewModel.swift
  Fitfty/Projects/Setting/Sources/SettingCoordinatorInterface.swift
  Fitfty/Projects/Setting/Sources/Utility/Model/Setting.swift
  Fitfty/Projects/Setting/Sources/Utility/Model/UserPrivacy.swift
  Fitfty/Projects/Setting/Sources/Utility/Views/UserInputView.swift
  Fitfty/Projects/Setting/Sources/View/FeedSettingHeaderView.swift
  Fitfty/Projects/Setting/Sources/Withdraw/WithdrawImageCell.swift
  Fitfty/Projects/Setting/Sources/Withdraw/WithdrawViewController.swift
  Fitfty/Projects/Setting/Sources/Withdraw/WithdrawViewModel.swift
Labels: ✨기능, D-1

#39 [Refactor] 메인피드 버그 개선
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
Labels: 🐛 버그, D-0

#40 [Feature] Profile 모듈 작업, 신고 작업, 게시글 수정 삭제 작업
  Fitfty/.swiftlint.yml
  Fitfty/Projects/Common/Sources/Extension/Date+extension.swift
  Fitfty/Projects/Common/Sources/Extension/String+extension.swift
  Fitfty/Projects/Common/Sources/ProfilePresentType.swift
  Fitfty/Projects/Common/Sources/ProfileType.swift
  Fitfty/Projects/Common/Sources/ReportType.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/MainCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/MyFitftyCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/DetailReportCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/PostCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ProfileCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ReportCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Network/Request/Report/PostReportReqeust.swift
  Fitfty/Projects/Core/Sources/Network/Request/Report/UserReportRequest.swift
  Fitfty/Projects/Core/Sources/Network/Response/FitftyReseponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/MyFitfty/ModifyMyFitftyResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/MyFitfty/UploadMyFitftyResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Post/PostResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Profile/ProfileResponse.swift
  Fitfty/Projects/Core/Sources/Repositories/FitftyRepository.swift
  Fitfty/Projects/Core/Sources/Utilities/UserManager.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/MainCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainFeedSection.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/UploadCody/ContentCell.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/PostCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/ProfileCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/ReportCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/DetailReportType.swift
  Fitfty/Projects/Profile/Sources/Post/ViewControllers/MyPostBottomSheetViewController.swift
  Fitfty/Projects/Profile/Sources/Post/ViewControllers/PostViewController.swift
  Fitfty/Projects/Profile/Sources/Post/ViewModel/PostBottomSheetViewModel.swift
  Fitfty/Projects/Profile/Sources/Post/ViewModel/PostViewModel.swift
  Fitfty/Projects/Profile/Sources/Post/Views/PostInfoView.swift
  Fitfty/Projects/Profile/Sources/Post/Views/PostView.swift
  Fitfty/Projects/Profile/Sources/Profile/MenuType.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/DetailReportViewController.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/ProfileViewController.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/ReportViewController.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewModel/DetailReportSection.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewModel/DetailReportViewModel.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewModel/ProfileSection.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewModel/ProfileViewModel.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/EmptyView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/FeedImageCell.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/MenuView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/MiniProfileView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/MyProfileHeaderView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/ProfileView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/Report/AllReportView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/Report/ReportCell.swift
  Fitfty/Tuist/ProjectDescriptionHelpers/Dependency+SPM.swift
Labels: 🖥네트워킹, D-0

#41 [Refactor] 메인피드 개선 (프로필 이미지, 주소)
  Fitfty/Projects/Common/Resources/Images.xcassets/ProfileDummy.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/ProfileDummy.imageset/ProfileDummy.png
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/CodyCell.swift
Labels: 🐛 버그, D-0

#45 [Feature] 게시글에서 계정 신고 추가
  Fitfty/Projects/Common/Sources/ReportPresentType.swift
  Fitfty/Projects/Coordinator/Sources/Profile/DetailReportCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/PostCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ProfileCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ReportCoordinator.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/PostCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/CoordinatorInterfaces/ReportCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/Post/ViewControllers/MyPostBottomSheetViewController.swift
  Fitfty/Projects/Profile/Sources/Post/ViewControllers/PostViewController.swift
  Fitfty/Projects/Profile/Sources/Post/Views/MyPostBottomSheetView.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/ReportViewController.swift
  Fitfty/Projects/Profile/Sources/Report/DetailReportType.swift
  Fitfty/Projects/Profile/Sources/Report/ViewControllers/DetailReportViewController.swift
  Fitfty/Projects/Profile/Sources/Report/ViewControllers/ReportViewController.swift
  Fitfty/Projects/Profile/Sources/Report/ViewModel/DetailReportSection.swift
  Fitfty/Projects/Profile/Sources/Report/ViewModel/DetailReportViewModel.swift
  Fitfty/Projects/Profile/Sources/Report/Views/ReportCell.swift
Labels: ✨기능, 🖥네트워킹, D-0, 💄UI

#48 [Refactor] 내 프로필 메뉴 탭 자연스럽게 개선
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/ProfileViewController.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/ProfileView.swift
Labels: ♻️리팩토링, D-1

#50 [Fix] 개인정보설정 저장 버그 수정, 문의하기 추가
  Fitfty/Projects/Core/Sources/Error/SettingError.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Onboarding/Sources/Nickname/NicknameView.swift
  Fitfty/Projects/Setting/Sources/Home/View/SettingCell.swift
  Fitfty/Projects/Setting/Sources/Home/ViewController/SettingViewController.swift
  Fitfty/Projects/Setting/Sources/PersonalInfo/ViewController/PersonalInfoViewController.swift
  Fitfty/Projects/Setting/Sources/Utility/Model/Setting.swift
Labels: 🐛 버그, D-0

#51 [Refactor] 프로필, 내핏프티 개선
  Fitfty/Projects/Coordinator/Sources/Profile/ProfileCoordinator.swift
  Fitfty/Projects/Core/Sources/Error/MyFitftyError.swift
  Fitfty/Projects/Core/Sources/LocalStorage.swift
  Fitfty/Projects/Core/Sources/Utilities/UserManager.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/Views/UploadCody/ContentCell.swift
  Fitfty/Projects/Profile/Sources/Post/ViewControllers/PostViewController.swift
  Fitfty/Projects/Profile/Sources/Post/ViewModel/PostViewModel.swift
  Fitfty/Projects/Profile/Sources/Post/Views/MyPostBottomSheetView.swift
  Fitfty/Projects/Profile/Sources/Post/Views/PostInfoView.swift
  Fitfty/Projects/Profile/Sources/Post/Views/PostView.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/ProfileViewController.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewModel/ProfileSection.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewModel/ProfileViewModel.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/MenuView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/MyProfileHeaderView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/ProfileView.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/UserProfileHeaderView.swift
  Fitfty/Projects/Setting/Sources/Profile/ViewController/ProfileSettingViewController.swift
  Fitfty/Projects/Setting/Sources/Profile/ViewModel/ProfileSettingViewModel.swift
Labels: 🐛 버그, ♻️리팩토링, D-0

#47 [Feature] 관리자 계정일때 신고 리스트 조회 구현
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Setting/ReportListCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Setting/SettingCoordinator.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/PostReportListResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/UserPrivacyResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Setting/UserReportListResponse.swift
  Fitfty/Projects/Core/Sources/Repositories/FitftyRepository.swift
  Fitfty/Projects/Core/Sources/Utilities/UserManager.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
  Fitfty/Projects/Setting/Sources/Admin/VewController/ReportListViewController.swift
  Fitfty/Projects/Setting/Sources/Admin/ViewModel/ReportListSection.swift
  Fitfty/Projects/Setting/Sources/Admin/ViewModel/ReportListViewModel.swift
  Fitfty/Projects/Setting/Sources/Admin/Views/ReportListCell.swift
  Fitfty/Projects/Setting/Sources/Admin/Views/ReportMenuView.swift
  Fitfty/Projects/Setting/Sources/Home/ViewController/SettingViewController.swift
  Fitfty/Projects/Setting/Sources/ReportListCoordinatorInterface.swift
  Fitfty/Projects/Setting/Sources/SettingCoordinatorInterface.swift
  Fitfty/Projects/Setting/Sources/Utility/Model/Setting.swift
  README.md
Labels: ✨기능, 🖥네트워킹, D-1, 💄UI

#49 [Refactor] QA - 메인피드 화면 개선
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_home.fill.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_home.fill.imageset/icon_home.fill.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_home.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_home.imageset/icon_home.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_sun.fill.imageset/icon_sun.fill.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/icons/icon_sun.imageset/icon_sun.svg
  Fitfty/Projects/Common/Sources/AppAppearance.swift
  Fitfty/Projects/Common/Sources/TabBarController.swift
  Fitfty/Projects/Common/Sources/WeatherTag.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/Core/Sources/Error/MainFeedError.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Repositories/AddressRepository.swift
  Fitfty/Projects/Core/Sources/Repositories/WeatherRepository.swift
  Fitfty/Projects/Core/Sources/Utilities/LocationConverter.swift
  Fitfty/Projects/Core/Sources/Utilities/LocationManager.swift
  Fitfty/Projects/Core/Sources/Utilities/UserManager.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewController/AddressViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Address/ViewModel/AddressViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Utilities/ViewModelError.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewController/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/CodyCellViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/ViewModel/WeatherInfoHeaderViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/CodyCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Home/Views/LocationView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewController/WeatherViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Weather/ViewModel/WeatherViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Welcome/ViewModel/WelcomeViewModel.swift
  Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
  Fitfty/Projects/Profile/Sources/Profile/ViewControllers/ProfileViewController.swift
  Fitfty/Projects/Profile/Sources/Profile/Views/FeedImageCell.swift
Labels: 🐛 버그, ♻️리팩토링, D-1, 💄UI
