Repository YAPP-Github/21st-iOS-Team-2-iOS, pull requests merged in 2023-01, with the labels that each got.

#10 [Feature] BottomSheetViewController 구현
  Fitfty/Projects/App/Project.swift
  Fitfty/Projects/Common/Sources/BottomSheetViewController.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/AddressCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/MainCoordinator.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/MainCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/ViewControllers/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/ViewModels/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Views/StyleCell.swift
Labels: ✨기능, D-3

#11 [Feature] 코디 등록 UI 구현
  Fitfty/.swiftlint.yml
  Fitfty/Projects/App/Project.swift
  Fitfty/Projects/App/Support/Info.plist
  Fitfty/Projects/Common/Resources/Images.xcassets/BtnInstagram.imageset/BtnInstagram.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/BtnInstagram.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnAlbumSelected.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnAlbumSelected.imageset/btnAlbumSelected.svg
  Fitfty/Projects/Common/Resources/Images.xcassets/btnAlbumUnSelcted.imageset/Contents.json
  Fitfty/Projects/Common/Resources/Images.xcassets/btnAlbumUnSelcted.imageset/btnAlbumUnSelcted.svg
  Fitfty/Projects/Common/Sources/Extension/Notification.Name+extension.swift
  Fitfty/Projects/Common/Sources/HeaderView.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/AlbumCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/UploadCodyCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/UploadCodyCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/Main/ViewControllers/AddressViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/ViewControllers/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/ViewControllers/TabBarController.swift
  Fitfty/Projects/MainFeed/Sources/Main/ViewModels/AddressViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/ViewModels/MainViewModel.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Address/AddressCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Address/AddressInfoView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/CodyCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/FooterView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/HeaderView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/LocationView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/StyleCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/WeatherCell.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/WeatherInfoHeaderView.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/WeatherInfoView.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Model/AlbumInfo.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Model/StyleTag.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Model/WeatherTag.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/PhotoService.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/ViewControllers/AlbumViewController.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/ViewControllers/UploadCodyViewController.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/Album/AlbumCell.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/Album/BarView.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/UploadCody/ContentCell.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/UploadCody/StyleTagCell.swift
  Fitfty/Projects/MainFeed/Sources/UploadCody/Views/UploadCody/WeatherTagCell.swift
  Fitfty/Projects/Profile/Sources/View/Post/PostView.swift
  Fitfty/Projects/Profile/Sources/View/Profile/FeedImageCell.swift
  Fitfty/Projects/Profile/Sources/View/Profile/HeaderView.swift
  Fitfty/Projects/Profile/Sources/View/Profile/MenuView.swift
  Fitfty/Projects/Profile/Sources/View/Profile/ProfileView.swift
  Fitfty/Projects/Profile/Sources/ViewController/PostViewController.swift
  Fitfty/Projects/Profile/Sources/ViewController/ProfileViewController.swift
Labels: 💄UI, D-3

#14 [Feature] User 프로필 UI 구현
  Fitfty/Projects/Common/Sources/Extension/UINavigationController+extension.swift
  Fitfty/Projects/Coordinator/Sources/Coordinator.swift
  Fitfty/Projects/Coordinator/Sources/Main/MainCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/ProfileCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/Profile/UserCoordinator.swift
  Fitfty/Projects/Coordinator/Sources/TabCoordinator.swift
  Fitfty/Projects/MainFeed/Sources/CoordinatorInterfaces/MainCoordinatorInterface.swift
  Fitfty/Projects/MainFeed/Sources/Main/ViewControllers/MainViewController.swift
  Fitfty/Projects/MainFeed/Sources/Main/Views/Main/CodyCell.swift
  Fitfty/Projects/Profile/Sources/MyProfile/ViewControllers/MyPostViewController.swift
  Fitfty/Projects/Profile/Sources/MyProfile/ViewControllers/MyProfileViewController.swift
  Fitfty/Projects/Profile/Sources/MyProfile/Views/Post/PostInfoView.swift
  Fitfty/Projects/Profile/Sources/MyProfile/Views/Post/PostView.swift
  Fitfty/Projects/Profile/Sources/MyProfile/Views/Profile/FeedImageCell.swift
  Fitfty/Projects/Profile/Sources/MyProfile/Views/Profile/MenuView.swift
  Fitfty/Projects/Profile/Sources/MyProfile/Views/Profile/MyProfileHeaderView.swift
  Fitfty/Projects/Profile/Sources/MyProfile/Views/Profile/ProfileView.swift
  Fitfty/Projects/Profile/Sources/MyProfileCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/UserProfile/ViewControllers/ReportViewController.swift
  Fitfty/Projects/Profile/Sources/UserProfile/ViewControllers/UserPostViewController.swift
  Fitfty/Projects/Profile/Sources/UserProfile/ViewControllers/UserProfileViewController.swift
  Fitfty/Projects/Profile/Sources/UserProfile/Views/UserProfileHeaderView.swift
  Fitfty/Projects/Profile/Sources/UserProfileCoordinatorInterface.swift
  Fitfty/Projects/Profile/Sources/View/Profile/ProfileView.swift
Labels: 💄UI, D-3

#15 Feature/component ios2 121
  Fitfty/Projects/Common/Sources/FitftyButton.swift
  Fitfty/Projects/Common/Sources/FitftyTextField.swift
Labels: D-1, 💄UI

#16 [Feature] 기상청 API, KakaoAK API를 활용하여 날씨 레파지토리, 주소 레파지토리를 구현
  Fitfty/.swiftlint.yml
  Fitfty/Projects/App/Support/Info.plist
  Fitfty/Projects/Common/Sources/Extension/CLLocationCoordinate2D+extension.swift
  Fitfty/Projects/Common/Sources/Extension/Date+extension.swift
  Fitfty/Projects/Common/Sources/Extension/Encodable+extension.swift
  Fitfty/Projects/Common/Sources/Extension/String+extension.swift
  Fitfty/Projects/Core/Project.swift
  Fitfty/Projects/Core/Sources/Model/Address.swift
  Fitfty/Projects/Core/Sources/Model/CurrentWeather.swift
  Fitfty/Projects/Core/Sources/Model/DailyWeather.swift
  Fitfty/Projects/Core/Sources/Model/MidTermForecast.swift
  Fitfty/Projects/Core/Sources/Model/ShortTermForecast.swift
  Fitfty/Projects/Core/Sources/Model/WeatherNow.swift
  Fitfty/Projects/Core/Sources/Network/FitftyAPI.swift
  Fitfty/Projects/Core/Sources/Network/KakaoAKAPI.swift
  Fitfty/Projects/Core/Sources/Network/Request/KakaoAK/AddressConversionRequest.swift
  Fitfty/Projects/Core/Sources/Network/Request/KakaoAK/SearchAddressRequest.swift
  Fitfty/Projects/Core/Sources/Network/Request/Weather/DailyWeatherListRequest.swift
  Fitfty/Projects/Core/Sources/Network/Request/Weather/MidTermForecastRequest.swift
  Fitfty/Projects/Core/Sources/Network/Request/Weather/ShortTermForecastRequest.swift
  Fitfty/Projects/Core/Sources/Network/Response/KakaoAK/AddressConversionResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/KakaoAK/SearchAddressResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Weather/DailyWeatherListResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Weather/MiddleWeatherTemperatureResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Weather/MidlandFcstResponse.swift
  Fitfty/Projects/Core/Sources/Network/Response/Weather/ShortTermForecastResponse.swift
  Fitfty/Projects/Core/Sources/Network/WeatherAPI.swift
  Fitfty/Projects/Core/Sources/Repositories/AddressRepository.swift
  Fitfty/Projects/Core/Sources/Repositories/WeatherRepository.swift
  Fitfty/Projects/Core/Sources/Utilities/APIKey.swift
  Fitfty/Projects/Core/Sources/Utilities/LocationConverter.swift
  Fitfty/Projects/Core/Sources/Utilities/LocationManager.swift
  Fitfty/Projects/Core/Sources/Utilities/Logger.swift
  Fitfty/Projects/Core/Sources/Utilities/WeatherTransferService.swift
  Fitfty/Projects/Core/Tests/WeatherAPITest.swift
Labels: ✨기능, 🖥네트워킹, D-4
